### PR TITLE
[Reviewer: Alex] Add in different signal handlers

### PR DESCRIPTION
**Pull request by eleanor-merry**
Alex, these are the changes to make the signal handler passed to the updater configurable

### CODE REVIEW

**Comment by AlexHockey** [comment]
Thanks for putting this PR together :-). 

It's a bit nasty that we have to expose a new template parameter to the `Updater` just to cope with the fact that the signal handler is itself templated. I think it would also be nice to have the `Updater` default to listening for `SIGHUP` rather than forcing each user to specify `_sighup_handler`

The only method that the updater calls on the signal handler is `wait_for_signal`. You could refactor this in to a purely virtual (non-templated) superclass (called, say, `SignalWaiter`), and have `SignalHandler` derive from that class and implement `wait_for_signal`. This means the `Updater` just has a pointer to `SignalWaiter` which is the same type no matter what signal handler is passed. 

Thoughts?

**Comment by AlexHockey** [comment]
I've made the changes I suggested. @bossmc is going to review as part of the rest of my Astaire work.

**Comment by bossmc** [comment]
I reviewed this as part of #276 right?

**Comment by AlexHockey** [comment]
Ah, yes, I forgot that merging this branch into my sto1162 branch would make this change appear in #276.

**Pull request merged**
