### PR TITLE
[Reviewer: Andy] Make DNS blacklist duration configurable

### PR DESCRIPTION
**Pull request by mirw**
Andy,

Please can you review this fix to make the DNS blacklist duration configurable?  There's no UT for this, but I've tested it live (and it's actually just refactoring).

Matt

### CODE REVIEW

**Comment by bossmc** [comment]
Code looks fine, does make me wonder why the blacklist is implemented in both HTTPResolver and SIPResolver rather than being generically in BaseResolver...

**Comment by mirw** [comment]
Sorry, I'm not sure I understand.  Can you elaborate?  Are you referring to the fact that BaseResolver requires create_blacklist to be called rather than creating the blacklist implicitly in the constructor?

**Comment by bossmc** [comment]
Ah, I got confused because `create_blacklist` and `destroy_blacklist` do nothing of the sort in `BaseResolver` which I assumed meant that the actual implementation was in `SIPResolver...`.  Turns out they're just odd.

**Comment by mirw** [comment]
Thanks - that makes sense.

**Pull request merged**
