### PR TITLE
[Reviewer: Matt] Remove 0MQ code from httpconnection.cpp entirely

### PR DESCRIPTION
**Pull request by rkd-msw**

### CODE REVIEW

**Comment by rkd-msw** [comment]
I realised that Sprout was the only user of this code, so it can now just go.

**Comment by mirw** [comment]
Looks good.  No comments.

**Comment by rkd-msw** [comment]
I've updated this to restore some locking around the stats changes (per my comments on https://github.com/Metaswitch/sprout/pull/1115).

**Comment by mirw** [comment]
Fine.

**Pull request merged**
